In [1]:
import numpy as np

In [5]:
A = np.random.random([2,1])
A

array([[0.33448323],
       [0.53128809]])

In [6]:
B=np.random.random([2,1])
A+B

array([[0.47097593],
       [1.3270624 ]])

In [7]:
np.add(A,B)

array([[0.47097593],
       [1.3270624 ]])

In [10]:
def neural_network(A,B):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    w=np.transpose(B)
    c=np.matmul(A, w)
    t=np.tanh(c)
    return t

In [11]:
neural_network(A, B)

array([[0.04562282, 0.26006038],
       [0.0723901 , 0.39927439]])

In [14]:
w=np.transpose(B)
c=np.matmul(w, A)
c

array([[0.46843993]])